
application_name = 'GPX Track Planner'

localizations = {
    'en': {
        'menu_file': 'File',
        'menu_file_open': 'Open GPX-File ...',
        'menu_file_open_filter': 'GPX Files (*.gpx);;All Files (*)',
        'menu_file_export': 'Export ...',
        'menu_settings': 'Settings',
        'menu_file_show_settings': 'Reveal in File System',
        'menu_file_exit': 'Exit',
        'menu_view': 'View',
        'menu_view_show_canvas_toolbar': 'Show Elevation Profile Toolbar',
        'menu_view_show_table': 'Show Data Table',
        'menu_view_show_map': 'Show Map',
        'mapview_title': 'Map',
        'label_filter': 'Filter',
        'label_filter_width': 'Filter Width',
        'label_track_properties': 'Track Segment Properties',
        'label_speed_model': 'Speed Model',
        'label_fit_speed_model': 'Fit Parameters',
        'label_automatic_start_time': 'Automatic Start Time',
        'label_start_time': 'Start Time',
        'label_distance': 'Distance',
        'label_coordinates': 'Coordinates',
        'label_elevation': 'Elevation',
        'label_slope': 'Slope',
        'label_ascent': 'Ascent',
        'label_descent': 'Descent',
        'label_time': 'Time',
        'label_absolute_slope': 'Abs. Slope',
    },
    'de': {
        'menu_file': 'Datei',
        'menu_file_open': 'GPX-Datei öffnen ...',
        'menu_file_open_filter': 'GPX-Dateien (*.gpx);;Alle Dateien (*)',
        'menu_file_export': 'Exportieren ...',
        'menu_settings': 'Einstellungen',
        'menu_file_show_settings': 'Im Dateisystem anzeigen',
        'menu_file_exit': 'Beenden',
        'menu_view': 'Ansicht',
        'menu_view_show_canvas_toolbar': 'Höhenprofil Werkzeugleiste anzeigen',
        'menu_view_show_table': 'Daten-Tabelle anzeigen',
        'menu_view_show_map': 'Karte anzeigen',
        'label_filter': 'Filter',
        'label_filter_width': 'Filterbreite',
        'label_track_properties': 'Track Segment Eigenschaften',
        'label_speed_model': 'Geschwindigkeitsmodell',
        'label_fit_speed_model': 'Fit Parameter',
        'label_automatic_start_time': 'Autom. Startzeit',
        'label_start_time': 'Startzeit',
        'label_distance': 'Distanz',
        'label_coordinates': 'Koordinaten',
        'label_elevation': 'Höhe',
        'label_slope': 'Steigung',
        'label_ascent': 'Anstieg',
        'label_descent': 'Abstieg',
        'label_time': 'Zeit',
        'label_absolute_slope': 'Abs. Steigung',
        'mapview_title': 'Karte',
    }
}
